DROP TABLE IF EXISTS stock_histories CASCADE;

CREATE TABLE stock_histories (
  id serial PRIMARY KEY NOT NULL,
  stock_id integer NOT NULL UNIQUE REFERENCES stocks (id) ON DELETE CASCADE,
  TIME_SERIES_INTRADAY jsonb,
  TIME_SERIES_DAILY jsonb,
  TIME_SERIES_WEEKLY jsonb
);